apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: kubedepend
  labels:
      app: kubedepend-db-app
data:
   MYSQL_ROOT_PASSWORD: rootpass
   MYSQL_DATABASE: jobs
   MYSQL_USER: jobsuser
   MYSQL_PASSWORD: userpass

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: kubedepend
data:
  BACKEND_PORT: "8000"
  WORKER_HOST: kubedepend-worker
  WORKER_PORT: "5000"
  MYSQL_DB_HOST: kubedepend-db.kubedepend.svc.cluster.local
  MYSQL_DB_PORT: "3306"
  MYSQL_DB_DB_NAME: jobs
  ACTIVEMQ_BROKER_HOST: kubedepend-activemq.kubedepend.svc.cluster.local
  ACTIVEMQ_BROKER_PORT: "61616"
  ACTIVEMQ_WORKER_QUEUE: jobWorkerQueue
  ACTIVEMQ_BACKEND_QUEUE: jobBackendQueue

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: kubedepend
data:
  ACTIVEMQ_BROKER_HOST: kubedepend-activemq.kubedepend.svc.cluster.local
  ACTIVEMQ_BROKER_PORT: "61616"
  ACTIVEMQ_WORKER_QUEUE: jobWorkerQueue
  ACTIVEMQ_BACKEND_QUEUE: jobBackendQueue


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: kubedepend
data:
  CHOKIDAR_USEPOLLING: "true"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
  namespace: kubedepend
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
      worker_connections  1024;
    }


    http {
       # include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  'HOST $host ------- $remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;

        keepalive_timeout  65;

        map $http_upgrade $connection_upgrade {
            default upgrade;
            ''      close;
          }

        server {
          server_name    127.0.0.1 localhost;
          location /api {
            proxy_pass http://kubedepend-backend:8000;
            proxy_set_header Host $host;
          }

          location / {
            proxy_pass http://kubedepend-frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
          }
        }
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: measurement-proxy-config
  namespace: measurement-proxy
data:
  nginx.conf: |
    worker_processes  1;

    events {
        worker_connections  1024;
    }

    http {
      # include /etc/nginx/mime.types;

      # include /etc/nginx/common/http_head.conf;

      # resolver need in case of variable sub in locations -- replace value in initContainer
      resolver NAMESERVER valid=30s;

      # resolver need in case of variable sub in locations -- replace value in initContainer
      # resolver NAMESERVER valid=30s;

       server {
        listen 80;
        server_name    127.0.0.1 localhost;

        set $backend_service http://kubedepend-backend.kubedepend.svc.cluster.local:8000;

        location / {

          proxy_set_header Host               $http_host;
          proxy_set_header X-Forwarded-Proto  $scheme;
          proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Host   $http_host;
          proxy_set_header X-Forwarded-Server $host;
          proxy_set_header X-Forwarded-Port   $server_port;

          proxy_pass $backend_service;
        }
      }
    }

