apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: worker-hpa
    namespace: kubedepend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubedepend-worker-depl
  minReplicas: 1
  maxReplicas: 10
  metrics:
      - type: Object
        object:
          metric:
              name: {{ .Values.hpa.metricName }}
          describedObject:
              apiVersion: /v1
              kind: Namespace
              name: kubedepend
          target:
              type: Value
              value: "1"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30 # default is 300
      
