apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubedepend-db-pvc
  labels:
    app: kubedepend-db-app
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi