version: '3.1'

services:

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: morova/kubedepend-proxy:1.0
    # volumes: 
    #   - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      # - BACKEND=http://backend:8000
      - BACKEND=backend
      # - FRONTEND=http://frontend:3000
      - FRONTEND=frontend
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: morova/kubedepend-backend:1.0
    restart: always
    ports: 
      - "8000:8000"
    environment: 
      - BACKEND_PORT=8000
      - WORKER_HOST=worker
      - WORKER_PORT=5000
      - MYSQL_DB_HOST=db
      - MYSQL_DB_PORT=3306
      - MYSQL_DB_DB_NAME=jobs
    depends_on:
      - db
      - worker

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: morova/kubedepend-frontend:1.0
    volumes:
      - './frontend:/code'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      # - BACKEND_HOST=backend
      # - BACKEND_PORT=8000
      # - BACKEND_API_PATH=/api/v1
    stdin_open: true
  
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: morova/kubedepend-worker:1.0
    restart: always
    ports:
      - "5000:5000"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=jobs
      - MYSQL_USER=jobsuser
      - MYSQL_PASSWORD=userpass
    volumes: 
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

  activemq:
    image: bwolf/activemq-prometheus
    ports:
      - 61616:61616
      - 8161:8161
      - 8080:8080
  
volumes: 
  db-data: