version: '3.1'

services:

  worker:
    build: ./worker
    restart: always
    ports:
      - "5000:5000"
      
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=jobs
      - MYSQL_USER=jobsuser
      - MYSQL_PASSWORD=userpass
    volumes: 
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
volumes: 
  db-data: