# Default values for kafka-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: danielqsj/kafka-exporter
  tag: v1.4.2
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9308

kafkaExporter:
  kafka:
    servers:
      - kafka-service-0.kafka.svc.cluster.local:9092
      - kafka-service-1.kafka.svc.cluster.local:9093
      - kafka-service-2.kafka.svc.cluster.local:9094
    version: "2.5.0"

  sasl:
    enabled: false
    handshake: true
    username: ""
    password: ""
    mechanism: ""

  tls:
    enabled: false
    insecureSkipTlsVerify: false
    caFile: ""
    certFile: ""
    keyFile: ""

  log:
    verbosity: 0
    enableSarama: false

prometheus:
  serviceMonitor:
    enabled: false
    namespace: monitoring
    interval: "30s"
    additionalLabels:
      app: kafka-exporter
    metricRelabelings: {}

labels: {}
podLabels: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
