server:
  port: ${WORKER_PORT:5000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus


messaging: activemq

# ActiveMQ
activemq:
  broker:
    url: "tcp://${ACTIVEMQ_BROKER_HOST:localhost}:${ACTIVEMQ_BROKER_PORT:61616}?jms.prefetchPolicy.queuePrefetch=1"
  worker:
    queue: ${ACTIVEMQ_WORKER_QUEUE:jobWorkerQueue}
  backend:
    queue: ${ACTIVEMQ_BACKEND_QUEUE:jobBackendQueue}
  jobstatus:
    queue: ${ACTIVEMQ_JOBSTATUS_QUEUE:jobStatus}

# Kafka
kafka:
  bootstrap-servers: ${KAFKA_BROKER}
  topics:
    worker: jobWorkerTopic
    backend: jobBackendTopic
    jobstatus: jobStatus
  consumer:
    group-id: worker

# Hearbeats service
heartbeats:
  enabled: false