{
 "title": "K8S Dependability",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Needed Worker Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 + (org_apache_activemq_Broker_QueueSize{destinationName=\"jobWorkerQueue\", job=\"activemq\"} or absent(org_apache_activemq_Broker_QueueSize{destinationName=\"jobWorkerQueue\", job=\"activemq\", namespace=\"kubedepend\"}) - 1) + on(namespace) (( sum by (namespace) (worker_busy_threads{job=\"worker-pods\"} )) or label_replace(vector(0), \"namespace\", \"kubedepend\", \"\", \"\"))) / on(namespace) (kube_deployment_status_replicas{deployment=\"kubedepend-worker-depl\"})"
    }
   ]
  },
  {
   "title": "Worker deployment Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=\"kubedepend-worker-depl\"}",
     "legendFormat": "All"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable{deployment=\"kubedepend-worker-depl\"}",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Worker Queue Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_QueueSize{destinationName=\"jobWorkerQueue\", job=\"activemq\"} or absent(org_apache_activemq_Broker_QueueSize{destinationName=\"jobWorkerQueue\", job=\"activemq\", namespace=\"kubedepend\"}) - 1",
     "legendFormat": "{{destinationName}}"
    }
   ]
  },
  {
   "title": "Worker busy threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(worker_busy_threads{job=\"kubernetes-service-endpoints\"})"
    }
   ]
  },
  {
   "title": "Available worker ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(2 + kube_deployment_status_replicas_unavailable{deployment=\"kubedepend-worker-depl\"}) / kube_deployment_status_replicas{deployment=\"kubedepend-worker-depl\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=~\".*kubedepend-backend.*\"}[$__range])",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "title": "Not availability",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - sum_over_time(probe_success{instance=~\".*kubedepend-backend.*\"}[$__interval])) / count_over_time(probe_success{instance=~\".*kubedepend-backend.*\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Mean Time Between Failures (MTBF)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "15 * sum_over_time(probe_success{instance=~\".*kubedepend-backend.*\"}[$__range]) / (floor((changes(probe_success{instance=~\".*kubedepend-backend.*\"}[$__range]) + 1 + probe_success{instance=~\".*kubedepend-backend.*\"} offset $__range) / 2)) + 15 * (count_over_time(probe_success{instance=~\".*kubedepend-backend.*\"}[$__range]) - sum_over_time(probe_success{instance=~\".*kubedepend-backend.*\"}[$__range])) / (floor((changes(probe_success{instance=~\".*kubedepend-backend.*\"}[$__range]) + 2 - probe_success{instance=~\".*kubedepend-backend.*\"} offset $__range) / 2)) ",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "title": "Mean Time to First Failure (MTFF)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "App Availability",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum_over_time(probe_success{instance=~\".*kubedepend-proxy.*\"}[30m]) / count_over_time(probe_success{instance=~\".*kubedepend-proxy.*\"}[30m])"
    }
   ]
  },
  {
   "title": "App Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://kubedepend-proxy.kubedepend.svc.cluster.local:80\"}"
    }
   ]
  },
  {
   "title": "Mean Up Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "15 * sum_over_time(probe_success{instance=~\".*kubedepend-backend.*\"}[$__range]) / (floor((changes(probe_success{instance=~\".*kubedepend-backend.*\"}[$__range]) + 1 + probe_success{instance=~\".*kubedepend-backend.*\"} offset $__range) / 2))",
     "legendFormat": "MUT"
    }
   ]
  },
  {
   "title": "Mean Down Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "15 * (count_over_time(probe_success{instance=~\".*kubedepend-backend.*\"}[$__range]) - sum_over_time(probe_success{instance=~\".*kubedepend-backend.*\"}[$__range])) / (floor((changes(probe_success{instance=~\".*kubedepend-backend.*\"}[$__range]) + 2 - probe_success{instance=~\".*kubedepend-backend.*\"} offset $__range) / 2))",
     "legendFormat": "MDT"
    }
   ]
  }
 ]
}