# fault profiles target K8s objects only in the kubedepend namespace
# fault profiles are combinations of some categories of chaos experiments
# the mapping from fault profiles to the category combinations happens on the test framework side in python code
# each category of chaos experiments have 3 strength levels (low, medium, high)

# Categories

# only concerns the DB
ioChaos:
  enabled: false
  strength: medium

networkPartitionChaos:
  enabled: false
  strength: medium

networkDelayChaos:
  enabled: false
  strength: medium

  # application fault
podFailureChaos:
  enabled: false
  strength: medium

# rescheduling 
podKillChaos:
  enabled: false
  strength: medium

stressCpuChaos:
  enabled: false
  strength: medium

stressMemChaos:
  enabled: false
  strength: medium

# chaos action modes and values to use with them
mode:
  fixPercent:
    low: 20
    medium: 35
    high: 50