apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: burn-memory-proxy
  namespace: chaos-testing
spec:
  mode: one
  selector:
    namespaces:
      - kubedepend
    labelSelectors:
      "app": "kubedepend-proxy-app"
  stressors:
    memory:
      workers: 100
  duration: "30s"
  scheduler:
    cron: "@every 2m"