apiVersion: v1
kind: Namespace
metadata:
  name: kubedepend

---

apiVersion: v1
kind: Namespace
metadata:
  name: chaos-testing

---

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---

apiVersion: v1
kind: Namespace
metadata:
  name: measurement-proxy