apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedepend-backend-depl
  namespace: kubedepend
spec:
  selector:
    matchLabels:
      app: kubedepend-backend
  template:
    metadata:
      labels:
        app: kubedepend-backend
    spec:
      containers:
      - name: kubedepend-backend-cont
        image: morova/kubedepend-backend
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
          name: backend-port
