version: "3.9"
services:
  jenkins:
    build: .
    # a bit ugly
    user: root
    ports:
      - "8080:8080"
      - "9090:9090"
    # environment:
    volumes:
      - jenkins-vol:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker


volumes:
  jenkins-vol:

# admin/adminpass