def someVar = "test"

pipeline { 
    agent any 
    options {
        skipStagesAfterUnstable()
        skipDefaultCheckout()
/*        checkoutToSubdirectory('k8s') */
        timeout(time: 15, unit: 'MINUTES')
        timestamps()
    }



    environment {
        AWS_REGION="us-east-2"
    }

    stages {
        stage('Prepare build') {
            steps {
                checkout scm
                // sh "source /var/jenkins_home/.bashrc"
            }
        }

        stage('Set up AWS CLI') {
            steps {
                echo "Setup AWS CLI"
                withCredentials(
                    [
                        usernamePassword(
                            credentialsId: 'aws-key',
                            usernameVariable: 'AWS_ACCESS_KEY_ID',
                            passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                        ),
                        string(
                            credentialsId: 'aws-session-token',
                            variable: 'AWS_SESSION_TOKEN'
                        )
                    ]
                ) {
                    sh "/usr/bin/docker run \
                        --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                        --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
                        --env AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN \
                        amazon/aws-cli cloudformation list-stacks --region ${env.AWS_REGION}"
                }
                
            }
        }

        stage('Create CF stack') {
            steps {
                echo "Create CF stack"
            }
        }

        stage('Deployment') {
            steps {
                echo "Deployment"
            }
        }

        stage('Running tests') {
            steps {
                echo "Running tests"
            }
        }

        stage('Clean up') {
            steps {
                echo "Clean up"
            }
        }
    }
}