# Pod Kill action kills the specified pod (ReplicaSet or something similar might be needed to ensure the pod will be restarted).
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-frontend
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - kubedepend
    labelSelectors:
      "app": "kubedepend-frontend-app"
  scheduler:
    cron: "@every 1m"