apiVersion: v1
kind: Service
metadata:
  name: kafka-service-0
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      name: tcp-kafka
      protocol: TCP
  selector:
    app: kafka
    id: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-1
  labels:
    app: kafka
spec:
  ports:
    - port: 9093
      name: tcp-kafka
      protocol: TCP
  selector:
    app: kafka
    id: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-2
  labels:
    app: kafka
spec:
  ports:
    - port: 9094
      name: tcp-kafka
      protocol: TCP
  selector:
    app: kafka
    id: "2"