kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker-0
  labels:
    app: kafka
    id: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      serviceAccountName: {{ .Values.kafka.serviceAccount.name }}
      containers:
        - name: kafka
          image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 9092
              name: tcp-kafka
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
            - name: KAFKA_BROKER_ID
              value: "0"
            - name: KAFKA_LISTENERS
              value: LISTENER://:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "LISTENER://kafka-service-0.{{ .Release.Namespace }}.svc.cluster.local:9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "kafka-service-0.{{ .Release.Namespace }}.svc.cluster.local"
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: LISTENER
          resources:
            {{- toYaml .Values.kafka.resources | nindent 12 }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker-1
  labels:
    app: kafka
    id: "1"
spec:
  selector:
    matchLabels:
        app: kafka
        id: "1"
  template:
    metadata:
      labels:
        app: kafka
        id: "1"
    spec:
      serviceAccountName: {{ .Values.kafka.serviceAccount.name }}
      containers:
        - name: kafka
          image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 9093
              name: tcp-kafka
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LISTENERS
              value: LISTENER://:9093
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "LISTENER://kafka-service-1.{{ .Release.Namespace }}.svc.cluster.local:9093"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "kafka-service-1.{{ .Release.Namespace }}.svc.cluster.local"
            - name: KAFKA_ADVERTISED_PORT
              value: "9093"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: LISTENER
          resources:
            {{- toYaml .Values.kafka.resources | nindent 12 }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker-2
  labels:
    app: kafka
    id: "2"
spec:
  selector:
    matchLabels:
        app: kafka
        id: "2"
  template:
    metadata:
      labels:
        app: kafka
        id: "2"
    spec:
      serviceAccountName: {{ .Values.kafka.serviceAccount.name }}
      containers:
        - name: kafka
          image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 9094
              name: tcp-kafka
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
            - name: KAFKA_BROKER_ID
              value: "2"
            - name: KAFKA_LISTENERS
              value: LISTENER://:9094
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "LISTENER://kafka-service-2.{{ .Release.Namespace }}.svc.cluster.local:9094"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "kafka-service-2.{{ .Release.Namespace }}.svc.cluster.local"
            - name: KAFKA_ADVERTISED_PORT
              value: "9094"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: LISTENER
          resources:
            {{- toYaml .Values.kafka.resources | nindent 12 }}