# Network Partition action separates pods into several independent subnets by blocking communication between them.

apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partition-backend-to-db
  namespace: kubedepend
spec:
  action: partition
  mode: one
  selector:
    namespace:
      - kubedepend
    labelSelectors:
      "app": "kubedepend-backend-app"
  direction: both
  target:
    selector:
      namespaces:
        - kubedepend
      labelSelectors:
        "app": "kubedepend-db-app"
    mode: one
  duration: "5s"
  scheduler:
    cron: "@every 15s"