{{- if .Values.networkDelayChaos.enabled -}}
{{/*
This configuration causes a latency in the network connections of the target Pods
*/}}
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: schedule-network-delay
spec:
  schedule: '*/1 * * * *'
  historyLimit: 5
  concurrencyPolicy: 'Forbid'
  type: 'NetworkChaos'
  networkChaos:
    action: delay
    mode: fixed-percent
    {{- if eq .Values.networkDelayChaos.strength "low" }}
    value: {{ .Values.mode.fixPercent.low | quote }}
    {{- else if eq .Values.networkDelayChaos.strength "high" }}
    value: {{ .Values.mode.fixPercent.high | quote }}
    {{- else }}
    value: {{ .Values.mode.fixPercent.medium | quote }}
    {{- end }}
    selector:
      namespaces:
        - kubedepend
    delay:
      {{- if eq .Values.networkDelayChaos.strength "low" }}
      latency: "500ms"
      {{- else if eq .Values.networkDelayChaos.strength "high" }}
      latency: "2000ms"
      {{- else }}
      latency: "1000ms"
      {{- end }}
    duration: "60s"
{{- end }}