
{{- /*
Pod Kill action kills the specified pod (ReplicaSet or something similar might be needed to ensure the pod will be restarted).
*/}}
{{- if .Values.podKillChaos.enabled -}}
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: schedule-pod-kill-worker
spec:
  schedule: '*/3 * * * *'
  historyLimit: 5
  concurrencyPolicy: 'Forbid'
  type: 'PodChaos'
  podChaos:
    action: pod-kill
    mode: fixed-percent
    {{- if eq .Values.podKillChaos.strength "low" }}
    value: {{ .Values.mode.fixPercent.low | quote }}
    {{- else if eq .Values.podKillChaos.strength "high" }}
    value: {{ .Values.mode.fixPercent.high | quote }}
    {{- else }}
    value: {{ .Values.mode.fixPercent.medium | quote }}
    {{- end }}
    selector:
      namespaces:
        - kubedepend
    duration: "60s"
{{- end }}