{{- if .Values.stressMemChaos.enabled -}}

apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: schedule-burn-memory
spec:
  schedule: '*/2 * * * *'
  historyLimit: 5
  concurrencyPolicy: 'Forbid'
  type: 'StressChaos'
  stressChaos:
    mode: fixed-percent
    {{- if eq .Values.stressMemChaos.strength "low" }}
    value: {{ .Values.mode.fixPercent.low | quote }}
    {{- else if eq .Values.stressMemChaos.strength "high" }}
    value: {{ .Values.mode.fixPercent.high | quote }}
    {{- else }}
    value: {{ .Values.mode.fixPercent.medium | quote }}
    {{- end }}
    selector:
      namespaces:
        - kubedepend
    stressors:
      memory:
        {{- if eq .Values.stressMemChaos.strength "low" }}
        workers: 1
        {{- else if eq .Values.stressMemChaos.strength "high" }}
        workers: 3
        {{- else }}
        workers: 2
        {{- end }}
    duration: "60s"
{{- end }}