
messaging: activemq

useHeartbeats: false

kafka:
  address: kafka-service-0.kafka.svc.cluster.local:9092

hpa:
  metricName: needed-worker-ratio

backend:
  image:
    repository: morova/kubedepend-backend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

worker:
  image:
    repository: morova/kubedepend-worker
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""


