
messaging: activemq

backend:
  image:
    repository: morova/kubedepend-backend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

worker:
  image:
    repository: morova/kubedepend-worker
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""


